warden.settings:
  type: mapping
  label: Settings
  mapping:
    warden_allow_requests:
      type: boolean
    warden_public_allow_ips:
      type: string
    warden_server_host_path:
      type: string
    warden_http_username:
      type: string
    warden_http_password:
      type: string
    warden_token:
      type: string
    warden_match_contrib:
      type: boolean
    warden_match_custom:
      type: boolean
    warden_preg_match_custom:
      type: string
    warden_preg_match_contrib:
      type: string
    warden_match_core:
      type: boolean
